# Top-level nav for the default language (pt)
nav:
  - Início: pt/index.md
  - Catálogos:
      - Catálogos: pt/catalogs/index.md
      - LSDB:
          - LSDB: pt/lsdb/index.md
          - 2MASS: pt/lsdb/2mass.md
          - DELVE DR2: pt/lsdb/delve_dr2.md
          - DES: 
              - DES DR2: pt/lsdb/des_dr2.md
              - DES Y6 Gold: pt/lsdb/des_y6_gold.md
          - DESI:
              - DESI DR1 (z-catalog): pt/lsdb/desi_dr1_zcat.md
          - eRASS1 Main: pt/lsdb/erosita_dr1_main.md
          - Euclid Q1: pt/lsdb/euclid_q1.md
          - Gaia: 
              - Gaia DR3: pt/lsdb/gaia_dr3.md
          - GALEX: pt/lsdb/galex.md  
          - HSC:
              - HSC PDR3 g: pt/lsdb/hsc_pdr3_g.md 
              - HSC PDR3 r: pt/lsdb/hsc_pdr3_r.md 
              - HSC PDR3 i: pt/lsdb/hsc_pdr3_i.md 
              - HSC PDR3 z: pt/lsdb/hsc_pdr3_z.md 
              - HSC PDR3 y: pt/lsdb/hsc_pdr3_y.md 
          - LSST:
            - LSST DP1: pt/lsdb/lsst_dp1.md
            - LSST DP2: pt/lsdb/lsst_dp2.md
#              - Rubin DP1 Object (Lite): pt/lsdb/rubin_dp1_object_lite.md 
          - Pan-STARRS1:
              - Pan-STARRS1 (objects): pt/lsdb/ps1_objects.md 
              - Pan-STARRS1 (detection): pt/lsdb/ps1_detection.md
          - SDSS DR7 Spectra: pt/lsdb/sdss_dr7_spectra.md 
          - Skymapper:
            - DR4: pt/lsdb/skymapper_dr4.md
            - Photometry: pt/lsdb/skymapper_photometry.md
          - TESS:
            - Lightcurve: pt/lsdb/tess_lightcurve.md
            - TIC: pt/lsdb/tess_tic.md 
          - TNS: pt/lsdb/tns.md
          - VSX: pt/lsdb/vsx.md            
          - WISE:
              - AllWISE: pt/lsdb/wise_allwise.md
              - NEOWISE: pt/lsdb/wise_neowise.md
          - ZTF: 
              - ZTF DR14 Objects: pt/lsdb/ztf_dr14_objects.md
              - ZTF DR14 Source: pt/lsdb/ztf_dr14_source.md
              - ZTF DR23 Objects: pt/lsdb/ztf_dr23_objects.md
              - ZTF DR23 Lightcurves: pt/lsdb/ztf_dr23_lightcurves.md
              - ZTF DR24 Objects: pt/lsdb/ztf_dr24_objects.md
              - ZTF DR24 Lightcurves: pt/lsdb/ztf_dr24_lightcurves.md
      - Banco de Dados: pt/database/index.md
      - Ambiente HPC : 
          - Ambiente HPC: pt/hpc/index.md
          - DES:
              - DES DR2: pt/hpc/des_dr2.md
              - DES Y6 Gold: pt/hpc/des_y6_gold.md
          - LSST:
              - LSST DP0.2: pt/hpc/lsst_dp0.2.md
              - LSST DP1: pt/hpc/lsst_dp1.md
              - LSST DP2: pt/hpc/lsst_dp2.md
  - Imagens:
      - Imagens: pt/images/index.md
      - HiPS: pt/images/hips.md
      - FITS:
          - FITS: pt/images/fits/index.md
          - LSST DP1: pt/images/fits/lsst_dp1.md
  - Produtos científicos Avançados:
      - Produtos científicos avançados: pt/sci_products/index.md
      - DES Y6 Gold IR: pt/sci_products/des_y6_gold_ir.md
      - LSST Photo-z Server: pt/sci_products/pzserver.md
      - Redshifts Públicos: pt/sci_products/public_specz.md
      - Predições de Ocultações Estelares : es/sci_products/occultations.md 
      - Catálogos de Aglomerados WaZP: pt/sci_products/wazp.md
  - Documentação: pt/docs.md
  - Créditos: pt/credits.md
  - Suporte: pt/support.md   

# Site information
site_name:  Data 
site_author: LIneA Team 
site_url: "https://data.linea.org.br"
repo_name: linea-it/datasets
repo_url: https://github.com/linea-it/datasets
edit_uri: 'edit/main/docs'
use_directory_urls: false
copyright: 'Copyright &copy; 2006 - 2025 LIneA'

# Configuration
theme:
  name: material
  custom_dir: linea-theme
  logo: 'images/linea_horizontal.png'
  favicon: 'images/linea_favicon.png'
  font:
    text: Roboto, Arial
  features:
    - navigation.indexes
    - content.code.copy
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
      primary: '#00B1EB'
      accent: '#00B1EB'

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
      primary: '#283663'
      accent: '#00B1EB'
  icon:
    admonition:
      private: material/lock
      


extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: material/home-circle
      link: https://www.linea.org.br
    - icon: fontawesome/brands/github
      link: https://github.com/linea-it
    - icon: material/twitter
      link: https://twitter.com/linea_org
    - icon: material/instagram
      link: https://instagram.com/linea_org
    - icon: material/facebook
      link: https://facebook.com/linea.org
    - icon: material/youtube
      link: https://youtube.com/@linea_org

  
  alternate:
    - name: Português
      link: /pt/
      lang: pt
    - name: English
      link: /en/
      lang: en
    - name: Español
      link: /es/
      lang: es

# Extensions
markdown_extensions:
  - attr_list
  - meta
  - footnotes
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols:
      fractions: false
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.snippets
  - pymdownx.blocks.admonition:
      types:
        - private

# Plugins
plugins:
  - i18n:
      docs_structure: folder
      languages:
        - locale: pt
          name: Português
          build: true
          default: true
          site_name: "Data"
        - locale: en
          name: English
          build: true
          site_name: "Data"
          nav:
            - Home: en/index.md
            - Catalogs:
                - Catalogs: en/catalogs/index.md
                - LSDB Surveys:
                    - LSDB Surveys: en/lsdb/index.md
                    - 2MASS: en/lsdb/2mass.md
                    - DELVE DR2: en/lsdb/delve_dr2.md
                    - DES: 
                        - DES DR2: en/lsdb/des_dr2.md
                        - DES Y6 Gold: en/lsdb/des_y6_gold.md
                    - DESI:
                        - DESI DR1 (z-catalog): en/lsdb/desi_dr1_zcat.md           
                    - eRASS1 Main: en/lsdb/erosita_dr1_main.md
                    - Euclid Q1: en/lsdb/euclid_q1.md
                    - Gaia: 
                        - Gaia DR3: en/lsdb/gaia_dr3.md
                    - GALEX: en/lsdb/galex.md  
                    - HSC:
                        - HSC PDR3 g: en/lsdb/hsc_pdr3_g.md 
                        - HSC PDR3 r: en/lsdb/hsc_pdr3_r.md 
                        - HSC PDR3 i: en/lsdb/hsc_pdr3_i.md 
                        - HSC PDR3 z: en/lsdb/hsc_pdr3_z.md 
                        - HSC PDR3 y: en/lsdb/hsc_pdr3_y.md
                    - LSST:
                        - LSST DP1: en/lsdb/lsst_dp1.md
                        - LSST DP2: en/lsdb/lsst_dp2.md    
                        #- Rubin DP1 Object (Lite): en/lsdb/rubin_dp1_object_lite.md
                    - Pan-STARRS1:
                        - Pan-STARRS1 (objects): en/lsdb/ps1_objects.md 
                        - Pan-STARRS1 (detection): en/lsdb/ps1_detection.md                   
                    - SDSS DR7 Spectra: en/lsdb/sdss_dr7_spectra.md
                    - Skymapper:
                      - DR4: en/lsdb/skymapper_dr4.md
                      - Photometry: en/lsdb/skymapper_photometry.md
                    - TESS:
                      - Lightcurve: en/lsdb/tess_lightcurve.md
                      - TIC: en/lsdb/tess_tic.md 
                    - TNS: en/lsdb/tns.md
                    - VSX: en/lsdb/vsx.md            
                    - WISE:
                        - AllWISE: en/lsdb/wise_allwise.md
                        - NEOWISE: en/lsdb/wise_neowise.md
                    - ZTF: 
                        - ZTF DR14 Objects: en/lsdb/ztf_dr14_objects.md
                        - ZTF DR14 Source: en/lsdb/ztf_dr14_source.md
                        - ZTF DR23 Objects: en/lsdb/ztf_dr23_objects.md
                        - ZTF DR23 Lightcurves: en/lsdb/ztf_dr23_lightcurves.md
                        - ZTF DR24 Objects: en/lsdb/ztf_dr24_objects.md
                        - ZTF DR24 Lightcurves: en/lsdb/ztf_dr24_lightcurves.md
                - Database: en/database/index.md
                - HPC Environment: 
                    - HPC: en/hpc/index.md
                    - DES:
                        - DES DR2: en/hpc/des_dr2.md
                        - DES Y6 Gold: en/hpc/des_y6_gold.md
                    - LSST:
                        - LSST DP0.2: en/hpc/lsst_dp0.2.md
                        - LSST DP1: en/hpc/lsst_dp1.md
                        - LSST DP2: en/hpc/lsst_dp2.md
            - Images:
                - Images: en/images/index.md
                - HiPS: en/images/hips.md
                - FITS:
                    - FITS: en/images/fits/index.md
                    - LSST DP1: en/images/fits/lsst_dp1.md
            - Advanced Science Products:
                - Advanced Science Products: en/sci_products/index.md
                - DES Y6 Gold IR: en/sci_products/des_y6_gold_ir.md
                - LSST Photo-z Server: en/sci_products/pzserver.md
                - Public Redshifts: en/sci_products/public_specz.md
                - Stellar Occultations Predictions: en/sci_products/occultations.md 
                - WaZP Cluster Catalogs: en/sci_products/wazp.md
            - Documentation: en/docs.md
            - Credits: en/credits.md
            - Support: en/support.md

        - locale: es
          name: Español
          build: true
          nav:
            - Inicio: es/index.md
            - Catálogos:
                - Catálogos: es/catalogs/index.md
                - LSDB Surveys:
                    - LSDB Surveys: es/lsdb/index.md
                    - 2MASS: es/lsdb/2mass.md
                    - DELVE DR2: es/lsdb/delve_dr2.md
                    - DES: 
                        - DES DR2: es/lsdb/des_dr2.md
                        - DES Y6 Gold: es/lsdb/des_y6_gold.md
                    - DESI:
                        - DESI DR1 (z-catalog): es/lsdb/desi_dr1_zcat.md
                    - eRASS1 Main: es/lsdb/erosita_dr1_main.md
                    - Euclid Q1: es/lsdb/euclid_q1.md
                    - Gaia: 
                        - Gaia DR3: es/lsdb/gaia_dr3.md
                    - GALEX: es/lsdb/galex.md  
                    - HSC:
                        - HSC PDR3 g: es/lsdb/hsc_pdr3_g.md 
                        - HSC PDR3 r: es/lsdb/hsc_pdr3_r.md 
                        - HSC PDR3 i: es/lsdb/hsc_pdr3_i.md 
                        - HSC PDR3 z: es/lsdb/hsc_pdr3_z.md 
                        - HSC PDR3 y: es/lsdb/hsc_pdr3_y.md
                    - LSST:
                        - LSST DP1: es/lsdb/lsst_dp1.md
                        - LSST DP2: es/lsdb/lsst_dp2.md
                    - Pan-STARRS1:
                        - Pan-STARRS1 (objects): es/lsdb/ps1_objects.md 
                        - Pan-STARRS1 (detection): es/lsdb/ps1_detection.md                    
                    - SDSS DR7 Spectra: es/lsdb/sdss_dr7_spectra.md
                    - Skymapper:
                      - DR4: es/lsdb/skymapper_dr4.md
                      - Photometry: es/lsdb/skymapper_photometry.md
                    - TESS:
                      - Lightcurve: es/lsdb/tess_lightcurve.md
                      - TIC: es/lsdb/tess_tic.md 
                    - TNS: es/lsdb/tns.md
                    - VSX: es/lsdb/vsx.md            
                    - WISE:
                        - AllWISE: es/lsdb/wise_allwise.md
                        - NEOWISE: es/lsdb/wise_neowise.md
                    - ZTF: 
                        - ZTF DR14 Objects: es/lsdb/ztf_dr14_objects.md
                        - ZTF DR14 Source: es/lsdb/ztf_dr14_source.md
                        - ZTF DR23 Objects: es/lsdb/ztf_dr23_objects.md
                        - ZTF DR23 Lightcurves: es/lsdb/ztf_dr23_lightcurves.md
                        - ZTF DR24 Objects: es/lsdb/ztf_dr24_objects.md
                        - ZTF DR24 Lightcurves: es/lsdb/ztf_dr24_lightcurves.md
                - Base de datos: es/database/index.md
                - HPC Environment:
                    - HPC Environment: es/hpc/index.md
                    - DES:
                        - DES DR2: es/hpc/des_dr2.md
                        - DES Y6 Gold: es/hpc/des_y6_gold.md
                    - LSST:
                        - LSST DP0.2: es/hpc/lsst_dp0.2.md
                        - LSST DP1: es/hpc/lsst_dp1.md
                        - LSST DP2: es/hpc/lsst_dp2.md
            - Imágenes:
                - Imágenes: es/images/index.md
                - HiPS: es/images/hips.md
                - FITS:
                    - FITS: es/images/fits/index.md
                    - LSST DP1: es/images/fits/lsst_dp1.md
            - Productos científicos avanzados:
                - Productos científico avanzados: es/sci_products/index.md
                - DES Y6 Gold IR: es/sci_products/des_y6_gold_ir.md
                - LSST Photo-z Server: es/sci_products/pzserver.md                
                - Redshifts Públicos: es/sci_products/public_specz.md
                - Predicciones de Ocultações Estelares: es/sci_products/occultations.md 
                - Catálogos de Aglomerados WaZP: es/sci_products/wazp.md
            - Documentación: es/docs.md
            - Créditos: es/credits.md
            - Soporte: es/support.md

  - search:
      enabled: true
  - git-revision-date-localized:
      type: date

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
